// Remote associates (after Mednick's Remote Associates Test): three words, one word that links
// them all ("pine, crab, sauce" → apple). Trains loose, associative thinking: the answer
// usually pops up suddenly rather than step by step.
import { pickTiered } from '../_engine/tiered.js';

export const meta = {
  id: 'remote-associates',
  name: 'Remote associates',
  blurb: 'Three words, one hidden link. Pine, crab, sauce → apple.',
  howTo: ['Find one word that goes with all three (before or after each).', 'Type it and press Enter, or reveal once the timer allows.'],
  skills: ['language', 'logic'],
  durationRange: [60, 240],
  difficultyRange: [1, 10],
  offline: true,
  lang: ['en'],
};

// [level 1–3, three cue words, answer, the three compounds]
const RAW = [
  [1, 'cottage swiss cake', 'cheese', 'cottage cheese, Swiss cheese, cheesecake'],
  [1, 'cream skate water', 'ice', 'ice cream, ice skate, ice water'],
  [1, 'show life row', 'boat', 'showboat, lifeboat, rowboat'],
  [1, 'night wrist stop', 'watch', 'night watch, wristwatch, stopwatch'],
  [1, 'duck fold dollar', 'bill', 'duckbill, billfold, dollar bill'],
  [1, 'rocking wheel high', 'chair', 'rocking chair, wheelchair, high chair'],
  [1, 'dew comb bee', 'honey', 'honeydew, honeycomb, honeybee'],
  [1, 'fountain baking pop', 'soda', 'soda fountain, baking soda, soda pop'],
  [1, 'aid rubber wagon', 'band', 'band-aid, rubber band, bandwagon'],
  [1, 'flake mobile cone', 'snow', 'snowflake, snowmobile, snow cone'],
  [1, 'cracker fly fighter', 'fire', 'firecracker, firefly, firefighter'],
  [1, 'safety cushion point', 'pin', 'safety pin, pincushion, pinpoint'],
  [1, 'cane daddy plum', 'sugar', 'sugar cane, sugar daddy, sugar plum'],
  [1, 'dream break light', 'day', 'daydream, daybreak, daylight'],
  [1, 'fish mine rush', 'gold', 'goldfish, gold mine, gold rush'],
  [1, 'measure worm video', 'tape', 'tape measure, tapeworm, videotape'],
  [1, 'high district house', 'school', 'high school, school district, schoolhouse'],
  [1, 'loser throat spot', 'sore', 'sore loser, sore throat, sore spot'],
  [1, 'preserve ranger tropical', 'forest', 'forest preserve, forest ranger, tropical forest'],
  [1, 'political surprise line', 'party', 'political party, surprise party, party line'],
  [2, 'sense courtesy place', 'common', 'common sense, common courtesy, commonplace'],
  [2, 'worm shelf end', 'book', 'bookworm, bookshelf, bookend'],
  [2, 'piece mind dating', 'game', 'game piece, mind game, dating game'],
  [2, 'flower friend scout', 'girl', 'flower girl, girlfriend, girl scout'],
  [2, 'river note account', 'bank', 'riverbank, banknote, bank account'],
  [2, 'print berry bird', 'blue', 'blueprint, blueberry, bluebird'],
  [2, 'pie luck belly', 'pot', 'potpie, potluck, potbelly'],
  [2, 'opera hand dish', 'soap', 'soap opera, hand soap, dish soap'],
  [2, 'fur rack tail', 'coat', 'fur coat, coat rack, coattail'],
  [2, 'stick maker point', 'match', 'matchstick, matchmaker, match point'],
  [2, 'hound pressure shot', 'blood', 'bloodhound, blood pressure, bloodshot'],
  [2, 'wet law business', 'suit', 'wetsuit, lawsuit, business suit'],
  [2, 'board magic death', 'black', 'blackboard, black magic, Black Death'],
  [2, 'type ghost screen', 'writer', 'typewriter, ghostwriter, screenwriter'],
  [2, 'land hand house', 'farm', 'farmland, farmhand, farmhouse'],
  [2, 'mouse bear sand', 'trap', 'mousetrap, bear trap, sand trap'],
  [2, 'tank hill secret', 'top', 'tank top, hilltop, top secret'],
  [2, 'way board sleep', 'walk', 'walkway, boardwalk, sleepwalk'],
  [2, 'salt deep foam', 'sea', 'sea salt, deep sea, sea foam'],
  [2, 'boot summer ground', 'camp', 'boot camp, summer camp, campground'],
  [2, 'cross rain tie', 'bow', 'crossbow, rainbow, bow tie'],
  [2, 'palm shoe house', 'tree', 'palm tree, shoe tree, treehouse'],
  [3, 'age mile sand', 'stone', 'Stone Age, milestone, sandstone'],
  [3, 'envy golf beans', 'green', 'green with envy, golf green, green beans'],
  [3, 'elephant lapse vivid', 'memory', 'elephant memory, memory lapse, vivid memory'],
  [3, 'lick sprinkle mines', 'salt', 'salt lick, sprinkle salt, salt mines'],
  [3, 'shopping washer picture', 'window', 'window shopping, window washer, picture window'],
  [3, 'tooth potato heart', 'sweet', 'sweet tooth, sweet potato, sweetheart'],
  [3, 'cadet capsule ship', 'space', 'space cadet, space capsule, spaceship'],
  [3, 'falling actor dust', 'star', 'falling star, star actor, stardust'],
  [3, 'broken clear eye', 'glass', 'broken glass, clear glass, eyeglass'],
  [3, 'right cat carbon', 'copy', 'copyright, copycat, carbon copy'],
  [3, 'note dive chair', 'high', 'high note, high dive, high chair'],
  [3, 'control place rate', 'birth', 'birth control, birthplace, birth rate'],
  [3, 'iron shovel engine', 'steam', 'steam iron, steam shovel, steam engine'],
  [3, 'fox man peep', 'hole', 'foxhole, manhole, peephole'],
  [3, 'ticket shop broker', 'pawn', 'pawn ticket, pawnshop, pawnbroker'],
  [3, 'dust cereal fish', 'bowl', 'dust bowl, cereal bowl, fishbowl'],
  [3, 'widow bite monkey', 'spider', 'black widow spider, spider bite, spider monkey'],
  [3, 'carpet alert ink', 'red', 'red carpet, red alert, red ink'],
  [3, 'house thumb pepper', 'green', 'greenhouse, green thumb, green pepper'],
  [3, 'end line lock', 'dead', 'dead end, deadline, deadlock'],
  [3, 'nuclear feud album', 'family', 'nuclear family, family feud, family album'],
  [3, 'mate shoes total', 'running', 'running mate, running shoes, running total'],
  [3, 'sore shoulder sweat', 'cold', 'cold sore, cold shoulder, cold sweat'],
  [3, 'cover arm wear', 'under', 'undercover, underarm, underwear'],
  [3, 'inch deal peg', 'square', 'square inch, square deal, square peg'],
  [3, 'mill tooth dust', 'saw', 'sawmill, sawtooth, sawdust'],
  [3, 'way ground weather', 'fair', 'fairway, fairground, fair weather'],
  [3, 'base snow foot', 'ball', 'baseball, snowball, football'],
];

export const ITEMS = RAW.map(([level, cues, answer, compounds]) => ({
  level,
  prompt: cues.split(' ').join('  ·  '),
  answers: [answer],
  answerText: answer,
  explain: compounds,
  hint: `It starts with “${answer[0]}” and has ${answer.length} letters.`,
}));

export const makeItems = (rng, d) => pickTiered(rng, ITEMS, d, 6);
