// Word origins. `lang` is the language English borrowed the word from (or its source);
// `meaning` is the origin story in a few words.
export const ETYMOLOGY = [
  { word: 'quarantine', lang: 'Italian', meaning: 'from “quaranta giorni”, forty days of isolation for ships in Venice' },
  { word: 'disaster', lang: 'Italian', meaning: '“ill-starred”: from “astro”, a star, blamed for bad luck' },
  { word: 'muscle', lang: 'Latin', meaning: '“musculus”, a little mouse (a flexing muscle looked like one moving)' },
  { word: 'robot', lang: 'Czech', meaning: '“robota”, forced labour; coined in Karel Čapek’s 1920 play' },
  { word: 'algebra', lang: 'Arabic', meaning: '“al-jabr”, the reunion of broken parts' },
  { word: 'algorithm', lang: 'Arabic', meaning: 'from the name of the Persian mathematician al-Khwārizmī' },
  { word: 'alcohol', lang: 'Arabic', meaning: '“al-kuḥl”, kohl, a fine powder used as eye make-up' },
  { word: 'zero', lang: 'Arabic', meaning: '“ṣifr”, empty, via Italian “zefiro”' },
  { word: 'coffee', lang: 'Arabic', meaning: '“qahwa”, via Turkish “kahve” and Italian “caffè”' },
  { word: 'chocolate', lang: 'Nahuatl', meaning: 'the Aztec drink “chocolatl”, via Spanish' },
  { word: 'tomato', lang: 'Nahuatl', meaning: '“tomatl”, via Spanish' },
  { word: 'avocado', lang: 'Nahuatl', meaning: '“āhuacatl”, via Spanish' },
  { word: 'coyote', lang: 'Nahuatl', meaning: '“coyotl”, via Mexican Spanish' },
  { word: 'hurricane', lang: 'Taíno', meaning: '“hurakán”, a storm, via Spanish' },
  { word: 'canoe', lang: 'Taíno', meaning: '“canoa”, a dugout boat, via Spanish' },
  { word: 'barbecue', lang: 'Taíno', meaning: '“barbacoa”, a wooden frame for cooking or sleeping, via Spanish' },
  { word: 'tycoon', lang: 'Japanese', meaning: '“taikun”, a great lord (a title used for the shogun)' },
  { word: 'tsunami', lang: 'Japanese', meaning: '“tsu” harbour + “nami” wave' },
  { word: 'emoji', lang: 'Japanese', meaning: '“e” picture + “moji” character (not related to “emotion”)' },
  { word: 'kindergarten', lang: 'German', meaning: '“children’s garden”, named by Friedrich Fröbel' },
  { word: 'shampoo', lang: 'Hindi', meaning: '“chāmpo”, press or knead (a head massage)' },
  { word: 'pyjamas', lang: 'Hindi/Urdu', meaning: '“pāy-jāma”, a leg garment, from Persian' },
  { word: 'bungalow', lang: 'Hindi', meaning: '“banglā”, a house in the Bengal style' },
  { word: 'jungle', lang: 'Hindi', meaning: '“jangal”, from Sanskrit for wild, uncultivated land' },
  { word: 'loot', lang: 'Hindi', meaning: '“lūṭ”, plunder' },
  { word: 'yoghurt', lang: 'Turkish', meaning: '“yoğurt”' },
  { word: 'kiosk', lang: 'Turkish', meaning: '“köşk”, a garden pavilion, from Persian' },
  { word: 'orange', lang: 'Sanskrit', meaning: '“nāraṅga”, via Persian and Arabic; the colour was named after the fruit' },
  { word: 'sugar', lang: 'Sanskrit', meaning: '“śarkarā”, grit or gravel, via Persian and Arabic' },
  { word: 'safari', lang: 'Swahili', meaning: 'a journey, from Arabic “safar”' },
  { word: 'ketchup', lang: 'Hokkien Chinese', meaning: '“kê-tsiap”, a fermented fish sauce' },
  { word: 'tea', lang: 'Min Chinese', meaning: '“tê”, brought to Europe by Dutch traders' },
  { word: 'tattoo', lang: 'Polynesian', meaning: 'Tahitian/Samoan “tatau”, to mark' },
  { word: 'taboo', lang: 'Tongan', meaning: '“tapu”, set apart, forbidden' },
  { word: 'kangaroo', lang: 'Guugu Yimithirr', meaning: '“gangurru”, from an Aboriginal language of Queensland' },
  { word: 'vaccine', lang: 'Latin', meaning: '“vacca”, a cow: the first vaccine used cowpox' },
  { word: 'window', lang: 'Old Norse', meaning: '“vindauga”, wind eye' },
  { word: 'husband', lang: 'Old Norse', meaning: '“húsbóndi”, master of the house' },
  { word: 'sky', lang: 'Old Norse', meaning: '“ský”, a cloud' },
  { word: 'berserk', lang: 'Old Norse', meaning: '“berserkr”, bear-shirt: a warrior who fought in a frenzy' },
  { word: 'mortgage', lang: 'Old French', meaning: '“death pledge”: the deal dies when the debt is paid or the land is lost' },
  { word: 'salary', lang: 'Latin', meaning: '“salarium”, from “sal”, salt (why is uncertain; the “paid in salt” story is doubtful)' },
  { word: 'companion', lang: 'Latin', meaning: '“com” with + “panis” bread: someone you share bread with' },
  { word: 'candidate', lang: 'Latin', meaning: '“candidatus”, clothed in white, like Roman office-seekers in chalked togas' },
  { word: 'trivia', lang: 'Latin', meaning: '“trivium”, where three roads meet: common, everyday talk' },
  { word: 'sarcasm', lang: 'Greek', meaning: '“sarkazein”, to tear flesh' },
  { word: 'dinosaur', lang: 'Greek', meaning: '“deinos” terrible + “sauros” lizard; coined by Richard Owen in 1842' },
  { word: 'hippopotamus', lang: 'Greek', meaning: '“river horse”' },
  { word: 'telephone', lang: 'Greek', meaning: '“tele” far + “phōnē” voice' },
  { word: 'photograph', lang: 'Greek', meaning: '“phōs” light + “graphē” writing' },
  { word: 'democracy', lang: 'Greek', meaning: '“dēmos” people + “kratos” rule' },
  { word: 'panic', lang: 'Greek', meaning: 'from Pan, the god whose shout caused sudden fear' },
  { word: 'echo', lang: 'Greek', meaning: 'from Echo, a nymph who could only repeat others’ words' },
  { word: 'tantalize', lang: 'Greek', meaning: 'from Tantalus, forever reaching for fruit and water just out of reach' },
  { word: 'atlas', lang: 'Greek', meaning: 'from the Titan Atlas, who held up the sky; Mercator put him on a map book' },
  { word: 'cereal', lang: 'Latin', meaning: 'from Ceres, Roman goddess of grain' },
  { word: 'January', lang: 'Latin', meaning: 'from Janus, the two-faced god of doorways and beginnings' },
  { word: 'Wednesday', lang: 'Old English', meaning: 'Woden’s day' },
  { word: 'Thursday', lang: 'Old English', meaning: 'Thor’s day (Þunor’s day)' },
  { word: 'sandwich', lang: 'English', meaning: 'from John Montagu, 4th Earl of Sandwich' },
  { word: 'boycott', lang: 'English', meaning: 'from Captain Charles Boycott, ostracised by Irish tenants in 1880' },
  { word: 'guillotine', lang: 'French', meaning: 'from Joseph-Ignace Guillotin, who proposed a quicker execution method' },
  { word: 'nicotine', lang: 'French', meaning: 'from Jean Nicot, who brought tobacco to France' },
  { word: 'bankrupt', lang: 'Italian', meaning: '“banca rotta”, broken bench (a moneylender’s table)' },
  { word: 'nightmare', lang: 'Old English', meaning: '“mære”, a goblin believed to sit on sleepers’ chests' },
  { word: 'goodbye', lang: 'English', meaning: 'a contraction of “God be with ye”' },
  { word: 'silly', lang: 'Old English', meaning: '“sælig”, happy or blessed; the meaning drifted over centuries' },
  { word: 'nice', lang: 'Latin', meaning: '“nescius”, ignorant; it meant “foolish” in Middle English' },
  { word: 'clue', lang: 'English', meaning: 'from “clew”, a ball of thread, like the one Theseus followed out of the labyrinth' },
  { word: 'OK', lang: 'English', meaning: 'a joke abbreviation of “oll korrect”, Boston newspapers, 1839' },
  { word: 'avalanche', lang: 'French', meaning: 'Alpine French, influenced by “avaler”, to descend' },
  { word: 'magazine', lang: 'Arabic', meaning: '“makhāzin”, storehouses, via French' },
  { word: 'admiral', lang: 'Arabic', meaning: '“amīr al-”, commander of the…' },
];
