// Dated events for the chronology game (offline). Negative years are BC. Dates are the ones
// standard references agree on; where historians give a range, the usual single year is used.
const ROWS = [
  [-2560, 'The Great Pyramid of Giza is completed (approximately)'],
  [-1754, 'The Code of Hammurabi is written in Babylon (approximately)'],
  [-776, 'The first recorded Olympic Games are held in Olympia'],
  [-753, 'The traditional date of the founding of Rome'],
  [-563, 'The traditional birth year of Siddhartha Gautama, the Buddha'],
  [-490, 'The Battle of Marathon'],
  [-399, 'Socrates is sentenced to death in Athens'],
  [-323, 'Alexander the Great dies in Babylon'],
  [-221, 'Qin Shi Huang unifies China as its first emperor'],
  [-44, 'Julius Caesar is assassinated'],
  [-27, 'Augustus becomes the first Roman emperor'],
  [79, 'Mount Vesuvius buries Pompeii'],
  [105, 'Cai Lun improves papermaking in Han China (traditional date)'],
  [313, 'The Edict of Milan tolerates Christianity in the Roman Empire'],
  [476, 'The last Western Roman emperor, Romulus Augustulus, is deposed'],
  [622, 'Muhammad’s migration to Medina (the Hijra)'],
  [732, 'The Battle of Tours'],
  [800, 'Charlemagne is crowned emperor'],
  [1066, 'The Battle of Hastings'],
  [1088, 'The University of Bologna is founded (traditional date)'],
  [1206, 'Genghis Khan is proclaimed ruler of the Mongols'],
  [1215, 'Magna Carta is sealed'],
  [1271, 'Marco Polo sets out for Asia'],
  [1347, 'The Black Death reaches Europe'],
  [1368, 'The Ming dynasty is founded'],
  [1440, 'Gutenberg develops his movable-type printing press (approximately)'],
  [1453, 'Constantinople falls to the Ottoman Empire'],
  [1492, 'Columbus reaches the Caribbean'],
  [1498, 'Vasco da Gama reaches India by sea'],
  [1503, 'Leonardo da Vinci begins painting the Mona Lisa'],
  [1517, 'Martin Luther posts his Ninety-five Theses'],
  [1519, 'Magellan’s expedition sets out to sail around the world'],
  [1521, 'Tenochtitlan falls to Spanish and allied forces'],
  [1543, 'Copernicus publishes his Sun-centred model'],
  [1588, 'The Spanish Armada is defeated'],
  [1609, 'Galileo first turns a telescope to the sky'],
  [1616, 'William Shakespeare and Miguel de Cervantes die'],
  [1620, 'The Mayflower sails to America'],
  [1648, 'The Peace of Westphalia ends the Thirty Years’ War'],
  [1665, 'Robert Hooke publishes Micrographia and names the “cell”'],
  [1687, 'Newton publishes the Principia'],
  [1707, 'The Acts of Union create the Kingdom of Great Britain'],
  [1752, 'Benjamin Franklin’s kite experiment (as reported)'],
  [1769, 'James Watt patents his improved steam engine'],
  [1776, 'The US Declaration of Independence is signed'],
  [1789, 'The storming of the Bastille starts the French Revolution'],
  [1796, 'Edward Jenner tests the first vaccine, against smallpox'],
  [1804, 'Haiti declares independence'],
  [1810, 'Mexico’s war of independence begins'],
  [1815, 'The Battle of Waterloo'],
  [1819, 'The Battle of Boyacá secures the independence of New Granada (Colombia)'],
  [1825, 'The first public steam railway opens in England (Stockton and Darlington)'],
  [1839, 'Daguerre’s photographic process is announced'],
  [1848, 'Revolutions spread across Europe'],
  [1859, 'Darwin publishes On the Origin of Species'],
  [1861, 'The American Civil War begins'],
  [1865, 'Slavery is abolished in the United States (13th Amendment)'],
  [1869, 'The Suez Canal opens; Mendeleev presents his periodic table'],
  [1876, 'Alexander Graham Bell patents the telephone'],
  [1879, 'Edison demonstrates a long-lasting light bulb'],
  [1886, 'Karl Benz patents his motor car'],
  [1888, 'Brazil abolishes slavery'],
  [1895, 'Röntgen discovers X-rays'],
  [1896, 'The first modern Olympic Games, in Athens'],
  [1903, 'The Wright brothers’ first powered flight'],
  [1905, 'Einstein’s “miracle year”, including special relativity'],
  [1910, 'The Mexican Revolution begins'],
  [1912, 'The Titanic sinks'],
  [1914, 'World War I begins; the Panama Canal opens'],
  [1917, 'The Russian Revolution'],
  [1918, 'World War I ends'],
  [1920, 'Women win the vote in the United States (19th Amendment)'],
  [1922, 'The tomb of Tutankhamun is discovered'],
  [1928, 'Fleming discovers penicillin'],
  [1929, 'The Wall Street Crash'],
  [1939, 'World War II begins'],
  [1945, 'World War II ends; the United Nations is founded'],
  [1947, 'India and Pakistan become independent'],
  [1948, 'The Universal Declaration of Human Rights is adopted'],
  [1949, 'The People’s Republic of China is proclaimed'],
  [1953, 'The structure of DNA is published; Everest is first climbed'],
  [1955, 'Rosa Parks refuses to give up her bus seat'],
  [1957, 'Sputnik 1, the first artificial satellite, is launched'],
  [1959, 'The Cuban Revolution triumphs'],
  [1961, 'Yuri Gagarin becomes the first human in space'],
  [1963, 'Martin Luther King Jr. gives his “I Have a Dream” speech'],
  [1969, 'Apollo 11 lands on the Moon'],
  [1971, 'The first email is sent over ARPANET'],
  [1973, 'The first handheld mobile phone call'],
  [1977, 'Voyager 1 is launched'],
  [1981, 'The first space shuttle flight'],
  [1986, 'The Chernobyl disaster'],
  [1989, 'The Berlin Wall falls; the World Wide Web is proposed'],
  [1990, 'Nelson Mandela is released from prison; Hubble is launched'],
  [1991, 'The Soviet Union dissolves'],
  [1994, 'Nelson Mandela becomes president of South Africa'],
  [1997, 'Deep Blue beats Garry Kasparov at chess'],
  [1998, 'Google is founded'],
  [2001, 'Wikipedia is launched'],
  [2003, 'The Human Genome Project is completed'],
  [2004, 'Facebook is launched'],
  [2007, 'The first iPhone is released'],
  [2008, 'The Large Hadron Collider starts up'],
  [2012, 'The Higgs boson is discovered; Curiosity lands on Mars'],
  [2015, 'Gravitational waves are detected for the first time'],
  [2016, 'AlphaGo beats Lee Sedol at Go'],
  [2019, 'The first image of a black hole is published'],
  [2020, 'The COVID-19 pandemic is declared'],
  [2021, 'The James Webb Space Telescope is launched'],
];

export const EVENTS = ROWS.map(([year, text]) => ({ year, text }));
export const fmtYear = (y) => (y < 0 ? `${-y} BC` : y < 1000 ? `AD ${y}` : String(y));
