// Fermi questions: estimate to the right order of magnitude. Answers are commonly cited
// figures or back-of-envelope results; the explanation shows one way to get there.
export const FERMI = [
  { q: 'How many times does a human heart beat in an 80-year life?', a: 3e9, explain: '≈70 beats a minute × 60 × 24 × 365 × 80 ≈ 3 billion.' },
  { q: 'How many times does your heart beat in a day?', a: 1e5, explain: '≈70 a minute × 1,440 minutes ≈ 100,000.' },
  { q: 'How many breaths does an adult take in a day?', a: 2e4, explain: '≈14 a minute × 1,440 minutes ≈ 20,000.' },
  { q: 'How many seconds are there in a year?', a: 3.15e7, explain: '60 × 60 × 24 × 365 ≈ 31.5 million.' },
  { q: 'How many minutes are there in a year?', a: 525600, explain: '60 × 24 × 365 = 525,600.' },
  { q: 'How many years would it take to count to one billion, one number per second, non-stop?', a: 31.7, explain: '10⁹ seconds ÷ 31.5 million seconds a year ≈ 32 years.' },
  { q: 'How many hairs are on a typical human head?', a: 1e5, explain: 'About 100,000 (roughly 100–150 per cm² over ~700 cm² of scalp).' },
  { q: 'How far is the Moon from the Earth, in kilometres?', a: 384400, explain: 'On average about 384,400 km, roughly 30 Earth diameters.' },
  { q: 'How far is the Sun from the Earth, in kilometres?', a: 1.5e8, explain: 'About 150 million km (one astronomical unit); light takes about 8 minutes.' },
  { q: 'What is the circumference of the Earth, in kilometres?', a: 40075, explain: 'About 40,000 km; the metre was originally defined from it.' },
  { q: 'How fast does the ground at the equator move because of Earth’s rotation, in km/h?', a: 1670, explain: '40,000 km ÷ 24 h ≈ 1,670 km/h.' },
  { q: 'How fast does the Earth move around the Sun, in km per second?', a: 30, explain: '2π × 150 million km ÷ 31.5 million s ≈ 30 km/s.' },
  { q: 'How many people are alive in the world today?', a: 8.2e9, explain: 'A little over 8 billion (UN estimates, mid-2020s).' },
  { q: 'How many neurons are in a human brain?', a: 8.6e10, explain: 'About 86 billion, by the most cited modern count.' },
  { q: 'Roughly how many cells make up a human body?', a: 3e13, explain: 'Around 30–37 trillion, most of them red blood cells.' },
  { q: 'How many trees are there on Earth?', a: 3e12, explain: 'About 3 trillion, according to a 2015 global study.' },
  { q: 'How many ants are there on Earth?', a: 2e16, explain: 'About 20 quadrillion, according to a 2022 estimate.' },
  { q: 'How many stars are in the Milky Way?', a: 2e11, explain: 'Estimates range from 100 to 400 billion.' },
  { q: 'How old is the universe, in years?', a: 1.38e10, explain: 'About 13.8 billion years.' },
  { q: 'How old is the Earth, in years?', a: 4.54e9, explain: 'About 4.5 billion years.' },
  { q: 'How many litres of water are in an Olympic swimming pool?', a: 2.5e6, explain: '50 m × 25 m × 2 m = 2,500 m³ = 2.5 million litres.' },
  { q: 'How many golf balls would fit inside a school bus?', a: 5e5, explain: 'A bus holds ≈ 20–25 m³; a golf ball takes ≈ 40 cm³ packed, so ≈ 500,000.' },
  { q: 'How many piano tuners work in a city of 3 million people?', a: 100, explain: 'Classic Fermi problem: ~1 piano per 30 people × one tuning a year ÷ ~1,000 tunings per tuner a year ≈ 100.' },
  { q: 'How many litres of water does a person drink in a lifetime?', a: 6e4, explain: '≈2 litres a day × 365 × 80 ≈ 60,000 litres.' },
  { q: 'How many hours does a person sleep in an 80-year life?', a: 2.3e5, explain: '8 hours × 365 × 80 ≈ 230,000 hours, about 26 years.' },
  { q: 'How many times does a person blink in a waking day?', a: 1.5e4, explain: '≈15 blinks a minute × 16 waking hours ≈ 14,000.' },
  { q: 'How many words are in a typical adult novel?', a: 9e4, explain: 'Usually 70,000–100,000 words.' },
  { q: 'How many words did Shakespeare’s complete works contain?', a: 8.8e5, explain: 'Roughly 880,000 words.' },
  { q: 'How many words does a person speak in a day, on average?', a: 1.6e4, explain: 'A 2007 study recording people’s speech found about 16,000 for both men and women.' },
  { q: 'How many litres of blood are in an adult body?', a: 5, explain: 'About 5 litres (roughly 7% of body weight).' },
  { q: 'How many bones are in the adult human body?', a: 206, explain: '206 (babies have around 270; some fuse as we grow).' },
  { q: 'How many cups of coffee are drunk worldwide each day?', a: 2e9, explain: 'Commonly cited: about 2 billion.' },
  { q: 'How heavy is a large blue whale, in tonnes?', a: 150, explain: 'Adults are often 100–150 tonnes; the heaviest recorded near 190.' },
  { q: 'How much does the Great Pyramid of Giza weigh, in tonnes?', a: 6e6, explain: 'About 2.3 million blocks averaging ~2.5 tonnes ≈ 6 million tonnes.' },
  { q: 'How many kilometres of blood vessels are in a human body?', a: 1e5, explain: 'Often quoted as about 100,000 km, mostly capillaries.' },
  { q: 'How many days would it take to walk around the Earth at the equator, walking 8 hours a day?', a: 1000, explain: '40,000 km ÷ (5 km/h × 8 h) = 1,000 days.' },
  { q: 'How many grains of sand fit in a one-litre jar (fine sand)?', a: 5e6, explain: 'A 0.5 mm grain is ~0.1 mm³; a litre is 10⁶ mm³; with packing ≈ several million.' },
  { q: 'How many books are in a large national library, such as the Library of Congress?', a: 2.5e7, explain: 'The Library of Congress holds over 25 million catalogued books.' },
  { q: 'How many pages would it take to print one billion characters, at 3,000 characters a page?', a: 3.3e5, explain: '10⁹ ÷ 3,000 ≈ 333,000 pages.' },
  { q: 'How long does light take to travel from the Sun to the Earth, in seconds?', a: 499, explain: '150 million km ÷ 300,000 km/s ≈ 500 seconds, about 8 minutes 20 seconds.' },
];
