// Quotations for cryptograms. Every one comes from a work in the public domain (old enough, or a
// US government speech); sources are given so the credit shown after solving is accurate.
export const QUOTES = [
  { text: 'To be, or not to be, that is the question.', by: 'William Shakespeare, Hamlet' },
  { text: 'Brevity is the soul of wit.', by: 'William Shakespeare, Hamlet' },
  { text: 'Neither a borrower nor a lender be.', by: 'William Shakespeare, Hamlet' },
  { text: 'All the world’s a stage, and all the men and women merely players.', by: 'William Shakespeare, As You Like It' },
  { text: 'The course of true love never did run smooth.', by: 'William Shakespeare, A Midsummer Night’s Dream' },
  { text: 'We are such stuff as dreams are made on.', by: 'William Shakespeare, The Tempest' },
  { text: 'Cowards die many times before their deaths; the valiant never taste of death but once.', by: 'William Shakespeare, Julius Caesar' },
  { text: 'The fault, dear Brutus, is not in our stars, but in ourselves.', by: 'William Shakespeare, Julius Caesar' },
  { text: 'It was the best of times, it was the worst of times.', by: 'Charles Dickens, A Tale of Two Cities' },
  { text: 'It is a far, far better thing that I do, than I have ever done.', by: 'Charles Dickens, A Tale of Two Cities' },
  { text: 'It is a truth universally acknowledged, that a single man in possession of a good fortune, must be in want of a wife.', by: 'Jane Austen, Pride and Prejudice' },
  { text: 'Happy families are all alike; every unhappy family is unhappy in its own way.', by: 'Leo Tolstoy, Anna Karenina (tr. Constance Garnett)' },
  { text: 'When you have eliminated the impossible, whatever remains, however improbable, must be the truth.', by: 'Arthur Conan Doyle, The Sign of the Four' },
  { text: 'Why, sometimes I have believed as many as six impossible things before breakfast.', by: 'Lewis Carroll, Through the Looking-Glass' },
  { text: 'Hope is the thing with feathers that perches in the soul.', by: 'Emily Dickinson' },
  { text: 'Because I could not stop for Death, he kindly stopped for me.', by: 'Emily Dickinson' },
  { text: 'Two roads diverged in a wood, and I took the one less traveled by.', by: 'Robert Frost, The Road Not Taken (1916)' },
  { text: 'The woods are lovely, dark and deep, but I have promises to keep.', by: 'Robert Frost, Stopping by Woods on a Snowy Evening (1923)' },
  { text: 'Water, water, every where, nor any drop to drink.', by: 'Samuel Taylor Coleridge, The Rime of the Ancient Mariner' },
  { text: 'A thing of beauty is a joy for ever.', by: 'John Keats, Endymion' },
  { text: 'I wandered lonely as a cloud.', by: 'William Wordsworth' },
  { text: 'Tis better to have loved and lost than never to have loved at all.', by: 'Alfred, Lord Tennyson, In Memoriam' },
  { text: 'To err is human, to forgive divine.', by: 'Alexander Pope, An Essay on Criticism' },
  { text: 'A little learning is a dangerous thing.', by: 'Alexander Pope, An Essay on Criticism' },
  { text: 'Hope springs eternal in the human breast.', by: 'Alexander Pope, An Essay on Man' },
  { text: 'The pen is mightier than the sword.', by: 'Edward Bulwer-Lytton, Richelieu' },
  { text: 'Early to bed and early to rise makes a man healthy, wealthy, and wise.', by: 'Benjamin Franklin, Poor Richard’s Almanack' },
  { text: 'Well done is better than well said.', by: 'Benjamin Franklin, Poor Richard’s Almanack' },
  { text: 'If I have seen further it is by standing on the shoulders of giants.', by: 'Isaac Newton, letter to Robert Hooke (1675)' },
  { text: 'I think, therefore I am.', by: 'René Descartes, Discourse on the Method' },
  { text: 'The unexamined life is not worth living.', by: 'Socrates, in Plato’s Apology' },
  { text: 'Man is by nature a political animal.', by: 'Aristotle, Politics' },
  { text: 'Nature does nothing in vain.', by: 'Aristotle, Politics' },
  { text: 'A journey of a thousand miles begins with a single step.', by: 'Laozi, Tao Te Ching' },
  { text: 'Man is born free, and everywhere he is in chains.', by: 'Jean-Jacques Rousseau, The Social Contract' },
  { text: 'The heart has its reasons which reason knows nothing of.', by: 'Blaise Pascal, Pensées' },
  { text: 'He who has a why to live can bear almost any how.', by: 'Friedrich Nietzsche, Twilight of the Idols' },
  { text: 'Whereof one cannot speak, thereof one must be silent.', by: 'Ludwig Wittgenstein, Tractatus (tr. C. K. Ogden, 1922)' },
  { text: 'I came, I saw, I conquered.', by: 'Julius Caesar' },
  { text: 'Fortune favours the brave.', by: 'Latin proverb (Terence)' },
  { text: 'Pride goeth before destruction, and an haughty spirit before a fall.', by: 'Proverbs 16:18 (King James Version)' },
  { text: 'Knowledge is power.', by: 'Francis Bacon' },
  { text: 'Give me liberty, or give me death!', by: 'Patrick Henry (1775)' },
  { text: 'Four score and seven years ago our fathers brought forth on this continent a new nation.', by: 'Abraham Lincoln, Gettysburg Address' },
  { text: 'Government of the people, by the people, for the people, shall not perish from the earth.', by: 'Abraham Lincoln, Gettysburg Address' },
  { text: 'Ask not what your country can do for you; ask what you can do for your country.', by: 'John F. Kennedy, inaugural address (1961)' },
  { text: 'The only thing we have to fear is fear itself.', by: 'Franklin D. Roosevelt, inaugural address (1933)' },
  { text: 'I disapprove of what you say, but I will defend to the death your right to say it.', by: 'Evelyn Beatrice Hall, The Friends of Voltaire (1906)' },
  { text: 'Genius is one per cent inspiration and ninety-nine per cent perspiration.', by: 'Thomas Edison (as reported in 1903)' },
  { text: 'Imagination is more important than knowledge.', by: 'Albert Einstein, interview in The Saturday Evening Post (1929)' },
  { text: 'That which does not kill us makes us stronger.', by: 'Friedrich Nietzsche, Twilight of the Idols' },
  { text: 'Curiosity is one of the permanent and certain characteristics of a vigorous intellect.', by: 'Samuel Johnson, The Rambler' },
  { text: 'The beginning is the most important part of the work.', by: 'Plato, The Republic' },
  { text: 'Wonder is the feeling of a philosopher, and philosophy begins in wonder.', by: 'Plato, Theaetetus' },
];
