// Riddles, lateral-thinking "situation puzzles" and rebuses. Traditional folk riddles (public
// domain) and puzzles written for this app. Answers list the accepted phrasings; the first one
// is shown.

// [level 1–3, riddle, [accepted answers], hint?]
const RIDDLES = [
  [1, 'What has keys but can’t open locks?', ['A piano', 'piano', 'keyboard'], 'It makes music.'],
  [1, 'What has to be broken before you can use it?', ['An egg', 'egg']],
  [1, 'What is full of holes but still holds water?', ['A sponge', 'sponge']],
  [1, 'What gets wetter the more it dries?', ['A towel', 'towel']],
  [1, 'What has a neck but no head?', ['A bottle', 'bottle']],
  [1, 'What has hands but can’t clap?', ['A clock', 'clock', 'watch']],
  [1, 'What has one eye but can’t see?', ['A needle', 'needle']],
  [1, 'What goes up but never comes down?', ['Your age', 'age']],
  [1, 'What can you catch but not throw?', ['A cold', 'cold']],
  [1, 'What has many teeth but can’t bite?', ['A comb', 'comb', 'zip', 'zipper', 'saw']],
  [2, 'What runs but never walks, has a mouth but never talks, and has a bed but never sleeps?', ['A river', 'river', 'stream']],
  [2, 'The more you take, the more you leave behind. What are they?', ['Footsteps', 'footprints', 'steps']],
  [2, 'What can travel around the world while staying in a corner?', ['A stamp', 'stamp', 'postage stamp']],
  [1, 'What has a head and a tail but no body?', ['A coin', 'coin']],
  [2, 'What belongs to you, but other people use it more than you do?', ['Your name', 'name']],
  [1, 'Which building has the most stories?', ['A library', 'library']],
  [2, 'What has cities but no houses, forests but no trees, and water but no fish?', ['A map', 'map']],
  [1, 'I’m tall when I’m young and short when I’m old. What am I?', ['A candle', 'candle', 'pencil']],
  [2, 'What comes once in a minute, twice in a moment, but never in a thousand years?', ['The letter M', 'M', 'letter m']],
  [2, 'What can fill a room but takes up no space?', ['Light', 'air', 'sound']],
  [1, 'What goes through cities and fields but never moves?', ['A road', 'road', 'path']],
  [1, 'What has legs but doesn’t walk?', ['A table', 'table', 'chair']],
  [1, 'What kind of band never plays music?', ['A rubber band', 'rubber band', 'elastic band']],
  [2, 'What word is spelled incorrectly in every dictionary?', ['Incorrectly']],
  [2, 'What is always in front of you but can’t be seen?', ['The future', 'future']],
  [2, 'If you drop me I’m sure to crack, but smile at me and I’ll smile back. What am I?', ['A mirror', 'mirror']],
  [1, 'What has a thumb and four fingers but is not alive?', ['A glove', 'glove']],
  [2, 'What can you keep after giving it to someone?', ['Your word', 'word', 'a promise', 'promise']],
  [3, 'The person who makes it sells it. The person who buys it never uses it. The person who uses it never knows. What is it?', ['A coffin', 'coffin']],
  [2, 'What gets bigger the more you take away from it?', ['A hole', 'hole']],
  [1, 'What invention lets you look right through a wall?', ['A window', 'window']],
  [1, 'What has words but never speaks?', ['A book', 'book']],
  [1, 'What runs all the way around a yard without moving?', ['A fence', 'fence']],
  [2, 'What can’t talk but will reply when spoken to?', ['An echo', 'echo']],
  [3, 'Forward I am heavy, but backward I am not. What am I?', ['A ton', 'ton'], 'Read the answer backwards.'],
  [2, 'What has 13 hearts but no other organs?', ['A deck of cards', 'deck of cards', 'pack of cards', 'cards', 'deck']],
  [1, 'Which month has 28 days?', ['All of them', 'all', 'every month', 'all months']],
  [2, 'What is so fragile that saying its name breaks it?', ['Silence', 'silence']],
  [1, 'What goes up and down but doesn’t move?', ['A staircase', 'stairs', 'staircase', 'steps', 'temperature']],
  [2, 'What is black when you buy it, red when you use it, and grey when you throw it away?', ['Charcoal', 'coal']],
  [2, 'Where does today come before yesterday?', ['In the dictionary', 'dictionary']],
  [2, 'What begins with T, ends with T, and has T in it?', ['A teapot', 'teapot']],
  [1, 'What flies without wings?', ['Time', 'time']],
  [2, 'What is as light as a feather, yet the strongest person can’t hold it for five minutes?', ['Breath', 'your breath', 'air']],
  [2, 'What can be cracked, made, told and played?', ['A joke', 'joke']],
  [2, 'I have branches, but no fruit, trunk or leaves. What am I?', ['A bank', 'bank']],
  [3, 'Which four-letter word reads the same forwards, backwards and upside down?', ['NOON', 'noon']],
  [2, 'The more of it there is, the less you see. What is it?', ['Darkness', 'dark', 'fog']],
  [2, 'I shave every day, but my beard stays the same. Who am I?', ['A barber', 'barber']],
  [2, 'What kind of room has no doors or windows?', ['A mushroom', 'mushroom']],
  [2, 'What loses its head in the morning and gets it back at night?', ['A pillow', 'pillow']],
  [2, 'What can you hold in your right hand but never in your left hand?', ['Your left hand', 'left hand', 'left elbow', 'your left elbow']],
  [3, 'Two fathers and two sons go fishing. Each catches one fish, yet only three fish are caught. How?', ['Grandfather, father and son', 'three generations', 'grandfather father son']],
  [2, 'What is harder to catch the faster you run?', ['Your breath', 'breath']],
  [2, 'What starts with an E, ends with an E, but usually contains only one letter?', ['An envelope', 'envelope']],
  [1, 'What has a bark but no bite?', ['A tree', 'tree']],
  [3, 'Which travels faster: heat or cold?', ['Heat', 'heat'], 'You can catch one of them.'],
  [3, 'What word, when you take away the whole, still has some left?', ['Wholesome']],
  [2, 'What has one head, one foot and four legs?', ['A bed', 'bed']],
  [1, 'What goes up when the rain comes down?', ['An umbrella', 'umbrella']],
  [2, 'What is always coming but never arrives?', ['Tomorrow', 'tomorrow']],
  [1, 'Which weighs more: a kilogram of feathers or a kilogram of bricks?', ['Neither', 'same', 'they weigh the same', 'equal']],
  [1, 'What has a tongue but cannot talk?', ['A shoe', 'shoe', 'boot']],
  [2, 'Feed me and I live, give me a drink and I die. What am I?', ['Fire', 'fire', 'a fire']],
  [3, 'I have no life, but I can die. What am I?', ['A battery', 'battery']],
  [2, 'What has many needles but doesn’t sew?', ['A pine tree', 'pine', 'christmas tree', 'fir tree', 'porcupine', 'hedgehog', 'cactus']],
  [3, 'What is in seasons, seconds, centuries and minutes, but not in decades, years or days?', ['The letter N', 'N', 'letter n']],
  [3, 'What walks on four legs in the morning, two at noon, and three in the evening?', ['A human', 'human', 'man', 'person'], 'The Sphinx asked this. Think of a whole life as one day.'],
  [3, 'Poor people have it, rich people need it, and if you eat it you die. What is it?', ['Nothing', 'nothing']],
  [2, 'What can you break without touching it?', ['A promise', 'promise', 'silence', 'a record']],
  [1, 'What is easy to get into but hard to get out of?', ['Trouble', 'trouble', 'debt', 'bed']],
  [2, 'What tastes better than it smells?', ['A tongue', 'tongue']],
  [3, 'Mary’s father has five daughters: Nana, Nene, Nini and Nono. What is the fifth daughter called?', ['Mary']],
  [1, 'What comes down but never goes up?', ['Rain', 'rain', 'snow']],
  [2, 'What kind of coat is best put on wet?', ['A coat of paint', 'paint']],
  [2, 'Which letter of the alphabet holds the most water?', ['C', 'the letter c'], 'Say it out loud.'],
  [2, 'What is always answered but never asks a question?', ['A doorbell', 'doorbell', 'telephone', 'phone']],
  [2, 'What has no beginning, no end and no middle?', ['A circle', 'circle', 'doughnut', 'ring', 'donut']],
  [2, 'What can you serve but never eat?', ['A ball', 'ball', 'tennis ball', 'volleyball']],
  [2, 'What is at the end of a rainbow?', ['The letter W', 'W', 'letter w']],
  [1, 'What has a head like a cat, feet like a cat and a tail like a cat, but isn’t a cat?', ['A kitten', 'kitten']],
  [2, 'What word becomes shorter when you add two letters to it?', ['Short']],
  [2, 'If you have me, you want to share me. If you share me, you haven’t got me. What am I?', ['A secret', 'secret']],
  [2, 'What has a heart that doesn’t beat?', ['An artichoke', 'artichoke']],
  [2, 'What has keys and a space, but no room, and you can enter but not go inside?', ['A keyboard', 'keyboard']],
  [1, 'What is black and white and read all over?', ['A newspaper', 'newspaper']],
  [3, 'What is the beginning of eternity, the end of time and space, and the start of every end?', ['The letter E', 'E', 'letter e']],
  [2, 'I am an odd number. Take away one letter and I become even. What number am I?', ['Seven', '7']],
  [2, 'What has a thousand ears but can’t hear?', ['A cornfield', 'cornfield', 'field of corn', 'corn']],
  [2, 'What has four eyes but can’t see?', ['Mississippi']],
  [1, 'What kind of tree can you hold in your hand?', ['A palm', 'palm']],
  [1, 'What has a horn but does not honk?', ['A rhinoceros', 'rhino', 'rhinoceros', 'unicorn']],
  [2, 'What gets dirtier the more you wash?', ['Water', 'bathwater', 'the water']],
  [2, 'What stays where it is when it goes off?', ['An alarm clock', 'alarm', 'alarm clock']],
  // number and trick riddles
  [2, 'A clock takes 5 seconds to strike six. How long does it take to strike twelve?', ['11 seconds', '11'], 'Count the gaps, not the strikes.'],
  [2, 'If three cats catch three mice in three minutes, how many cats catch 100 mice in 100 minutes?', ['3', 'three']],
  [2, 'A bat and a ball cost 1.10 in total. The bat costs 1.00 more than the ball. How much is the ball?', ['0.05', '5 cents', 'five cents', '.05']],
  [1, 'How many times can you subtract 10 from 100?', ['Once', 'one', '1'], 'After the first time, it isn’t 100 any more.'],
  [1, 'A farmer has 17 sheep. All but 9 run away. How many are left?', ['9', 'nine']],
  [1, 'In a race, you overtake the person in second place. What place are you in now?', ['Second', '2nd', 'second place']],
  [2, 'A patch of lily pads doubles in size every day and covers the whole lake in 48 days. On which day does it cover half?', ['Day 47', '47']],
  [2, 'Five machines make five widgets in five minutes. How long do 100 machines take to make 100 widgets?', ['5 minutes', '5', 'five minutes']],
  [2, 'Divide 30 by a half and add 10. What do you get?', ['70', 'seventy']],
  [1, 'How many animals of each kind did Moses take on the ark?', ['None', 'zero', '0', 'no animals'], 'Who built the ark?'],
  [1, 'A rooster lays an egg on the peak of a roof. Which way does it roll?', ['Roosters don’t lay eggs', 'none', 'it doesn’t', 'roosters dont lay eggs', 'no egg']],
  [1, 'What do you get if you multiply all the digits on a phone keypad?', ['0', 'zero']],
  [3, 'I am a three-digit number. My tens digit is five more than my ones digit, and my hundreds digit is eight less than my tens digit. What am I?', ['194']],
  [1, 'There are three apples and you take away two. How many do you have?', ['2', 'two']],
  [2, 'A doctor gives you three pills and tells you to take one every half hour. How long do they last?', ['One hour', '1 hour', 'an hour', '60 minutes']],
  [2, 'How far can a dog run into a forest?', ['Halfway', 'half way'], 'After that, it’s running out.'],
  [3, 'What is the smallest whole number equal to seven times the sum of its digits?', ['21']],
  [1, 'Before Mount Everest was discovered, what was the highest mountain on Earth?', ['Mount Everest', 'everest']],
];

// [level, situation, answer, [accepted key words]]
const SITUATIONS = [
  [1, 'A man walks into a bar and asks for a glass of water. The bartender pulls out a gun and points it at him. The man says “Thank you” and leaves. Why?', 'He had hiccups. The water was one cure; the fright worked better.', ['hiccups']],
  [2, 'A man lives on the tenth floor. Every morning he takes the lift down. Coming home, he rides it to the seventh floor and walks up, unless it has rained or someone else is in the lift. Why?', 'He is too short to reach the “10” button. He can press it with his umbrella, or ask someone else.', ['short', 'reach', 'button']],
  [1, 'Romeo and Juliet are found dead on the floor. There is broken glass and a puddle of water. The window is open. What happened?', 'Romeo and Juliet are goldfish. The wind (or a cat) knocked their bowl off the table.', ['goldfish', 'fish', 'bowl']],
  [2, 'A woman shoots her husband, then holds him under water for five minutes, then hangs him. An hour later they go out to dinner together. How?', 'She is a photographer: she took his photo, developed it in a bath, and hung it up to dry.', ['photo', 'photograph', 'picture']],
  [1, 'A man pushes his car to a hotel and tells the owner he’s bankrupt. Why?', 'He is playing Monopoly.', ['monopoly', 'board game']],
  [2, 'A man is found dead in a field with an unopened package beside him. Nobody else is around. How did he die?', 'The package is a parachute that failed to open.', ['parachute']],
  [2, 'A cabin sits on a mountainside, with several dead people inside. What happened?', 'The “cabin” is the cabin of a plane that crashed.', ['plane', 'crash', 'aeroplane', 'airplane']],
  [1, 'A cowboy rides into town on Friday, stays three days, and leaves on Friday. How?', 'His horse is called Friday.', ['horse']],
  [1, 'A boy and his father are in a car crash. The father dies; the boy is rushed to hospital. The surgeon says, “I can’t operate: this boy is my son.” How?', 'The surgeon is his mother.', ['mother', 'mom', 'mum']],
  [2, 'Two people play five games of chess. Each wins the same number of games and there are no draws. How?', 'They weren’t playing against each other.', ['not playing each other', 'different opponents', 'each other']],
  [2, 'Two boys were born on the same day of the same year to the same mother, but they are not twins. How?', 'They are two of a set of triplets.', ['triplets', 'quadruplets']],
  [2, 'A man is found hanging in a locked, empty room. There is nothing in the room but a puddle of water under his feet. How did he get up there?', 'He stood on a block of ice, which melted.', ['ice']],
  [2, 'A man turns off the light and goes to sleep. In the morning he hears on the news that people died in the night, and he realises it was his fault. Why?', 'He was a lighthouse keeper; with the light off, a ship ran aground.', ['lighthouse']],
  [1, 'A man walks home in the rain with no hat or umbrella. His clothes are soaked, but not a hair on his head gets wet. How?', 'He is bald.', ['bald']],
  [1, 'Why can’t a man living in New York be buried in Chicago?', 'Because he’s living.', ['living', 'alive']],
  [2, 'A man jumps out of a window of a 20-storey building. He isn’t hurt at all. How?', 'He jumped out of a ground-floor window.', ['ground floor', 'first floor', 'ground']],
  [3, 'Two friends drink iced tea from the same jug. One drinks five glasses quickly and is fine. The other sips one glass slowly and is poisoned. Why?', 'The poison was in the ice. The fast drinker finished before it melted.', ['ice', 'melted']],
  [1, 'A woman drops her ring into a cup full of coffee, but the ring doesn’t get wet. How?', 'The coffee was dry: beans or grounds, not a drink.', ['beans', 'grounds', 'powder', 'dry']],
  [2, 'A lorry is stuck under a low bridge, wedged by just a few centimetres. How can it be freed without damaging the bridge?', 'Let some air out of its tyres.', ['tyres', 'tires', 'air']],
  [1, 'How can you throw a ball as hard as you can and have it come back to you, without it bouncing off anything or being tied to anything?', 'Throw it straight up.', ['up', 'straight up']],
  [1, 'A driver in a black car, with the headlights off and no moon, stops just in time for a woman in black crossing the road. How did he see her?', 'It was daytime.', ['day', 'daytime']],
  [1, 'You are driving a car. There is a gold door, a silver door and a bronze door. Which do you open first?', 'The car door.', ['car door', 'car']],
  [2, 'A butcher is 1.80 m tall and wears size 44 shoes. What does he weigh?', 'Meat.', ['meat']],
  [1, 'How can a man go eight days without sleep?', 'He sleeps at night.', ['night']],
  [2, 'Two people are born at the same moment, but they have different birthdays. How?', 'They were born in different time zones, on either side of midnight.', ['time zone', 'timezones', 'time zones']],
  [3, 'A man was born in 1955 and died in 1955, yet he was 70 years old when he died. How?', '1955 was the number of his hospital room, not the year.', ['room']],
  [1, 'A girl falls off a 10-metre ladder but isn’t hurt at all. How?', 'She fell off the bottom rung.', ['bottom', 'first step', 'bottom rung']],
  [1, 'A plane crashes exactly on the border between two countries. Where do they bury the survivors?', 'You don’t bury survivors.', ['survivors', 'don’t', 'dont', 'alive']],
  [2, 'A mother has seven children, and half of them are boys. How is that possible?', 'They are all boys (half are boys, and so is the other half).', ['all boys', 'all']],
  [2, 'Why are 1990 coins worth more than 1989 coins?', 'Because 1990 coins are one more coin than 1989 coins.', ['one more', 'more coins']],
  [3, 'The music stopped, and she died. What happened?', 'She was a tightrope walker performing blindfolded; the music was meant to stop only when she reached the end of the rope. It stopped too soon.', ['tightrope', 'blindfold']],
  [2, 'A man leaves home, turns left three times, and returns home to find two masked men waiting. Who are they?', 'He is playing baseball: the masked men are the catcher and the umpire.', ['baseball', 'catcher', 'umpire']],
  [3, 'Looking at a portrait, a man says: “Brothers and sisters I have none, but that man’s father is my father’s son.” Who is in the portrait?', 'His son.', ['son']],
  [2, 'There are six eggs in a basket. Six people each take one egg, yet one egg is still in the basket. How?', 'The last person took the basket with the egg still in it.', ['basket']],
  [2, 'A man builds a house with all four walls facing south. A bear walks past. What colour is the bear?', 'White: the house is at the North Pole, so it’s a polar bear.', ['white', 'polar']],
  [1, 'An electric train travels north. The wind blows west. Which way does the smoke go?', 'Electric trains don’t make smoke.', ['no smoke', 'none', 'electric']],
  [1, 'You walk into a cold, dark room with a candle, a wood stove and a gas lamp. You have one match. What do you light first?', 'The match.', ['match']],
  [3, 'The day before yesterday I was 25. Next year I will be 28. When is my birthday, and when am I saying this?', 'My birthday is 31 December, and I’m saying this on 1 January.', ['31 december', 'december 31', 'new year']],
  [1, 'Tom’s mother has three children: April, May and…?', 'Tom.', ['tom']],
  [2, 'A woman in a small town married 20 different men, yet she never divorced and none of them died. How?', 'She is a priest (or registrar) who married them to other people.', ['priest', 'minister', 'officiant', 'registrar', 'celebrant']],
  [2, 'A police officer sees a lorry driver going the wrong way down a one-way street, but doesn’t stop him. Why?', 'The driver was walking, not driving.', ['walking', 'on foot']],
  [2, 'A man went into a restaurant, ordered albatross, took one bite, and walked out upset. Why? (Classic; a bit dark.)', 'Years earlier, shipwrecked, he had been told the meat he ate to survive was albatross. Tasting real albatross, he realised it hadn’t been.', ['shipwreck', 'albatross', 'not albatross']],
];

// [level, picture (lines), [answers]]
const REBUSES = [
  [1, 'MIND\n——————\nMATTER', ['Mind over matter']],
  [1, 'STAND\n  I', ['I understand']],
  [1, 'HEAD\n——————\nHEELS', ['Head over heels']],
  [2, 'R|E|A|D|I|N|G', ['Reading between the lines']],
  [1, 'MAN\n——————\nBOARD', ['Man overboard', 'man over board']],
  [1, 'T\nO\nW\nN', ['Downtown', 'down town']],
  [2, 'ONCE\n——————\nTIME', ['Once upon a time']],
  [2, 'GROUND\n——————\nFEET FEET FEET\nFEET FEET FEET', ['Six feet under ground', 'six feet underground', 'six feet under']],
  [1, 'CYCLE CYCLE CYCLE', ['Tricycle']],
  [2, 'ECNALG', ['Backward glance', 'a backward glance', 'backwards glance']],
  [1, 'HISTORY HISTORY', ['History repeats itself', 'history repeats']],
  [2, 'WEAR\nLONG', ['Long underwear']],
  [2, 'TRAVEL\n——————\nC C C C C C C', ['Travel overseas']],
  [2, 'LE VEL', ['Split level', 'split-level']],
  [2, 'YOU  JUST  ME', ['Just between you and me']],
  [2, 'DEATH  LIFE', ['Life after death']],
  [2, 'HE’S  HIMSELF', ['He’s beside himself', 'hes beside himself', 'beside himself']],
  [1, 'SLEEPING\n——————\nJOB', ['Sleeping on the job']],
  [2, 'ARREST\n——————\nYOU’RE', ['You’re under arrest', 'youre under arrest', 'under arrest']],
  [2, 'DICE DICE', ['Paradise', 'pair of dice']],
  [1, 'BAN ANA', ['Banana split']],
  [2, 'EGGS\n——————\nEASY', ['Eggs over easy']],
  [1, 'T\nO\nU\nC\nH', ['Touchdown', 'touch down']],
  [2, 'I  RIGHT  I', ['Right between the eyes']],
  [2, 'ME  REPEAT', ['Repeat after me']],
  [1, 'SIDE SIDE', ['Side by side']],
  [2, 'SKATING\n——————\nTHIN ICE', ['Skating on thin ice']],
  [2, 'BUSINESS  PLEASURE', ['Business before pleasure']],
  [1, '┌─────┐\n│ BOX │  THINK\n└─────┘', ['Think outside the box']],
  [1, 'LOOK  LEAP', ['Look before you leap']],
  [2, '      ┌───────┐\nFISH  │ WATER │\n      └───────┘', ['Fish out of water', 'a fish out of water']],
  [2, 'GET IT GET IT GET IT GET IT', ['Forget it', 'for get it']],
  [2, 'A B C D E F G H I J K M N O P Q R S T U V W X Y Z', ['Noel', 'no l', 'no el']],
  [2, 'MILL1ON', ['One in a million']],
  [2, 'HOROBOD', ['Robin Hood', 'rob in hood']],
  [1, 'COF FEE', ['Coffee break']],
  [3, 'EVERYRIGHTTHING', ['Right in the middle of everything']],
  [2, 'STOOD\n——————\nMIS', ['Misunderstood']],
  [3, 'DOCS DOCS', ['Paradox', 'pair of docs']],
  [2, 'FEELING\n——————\nWEATHER', ['Feeling under the weather', 'under the weather']],
  [2, 'BRIDGE\n——————\nWATER', ['Water under the bridge']],
  [1, 'CHEEK CHEEK', ['Cheek to cheek']],
  [2, 'SITTING\n——————\nWORLD', ['Sitting on top of the world', 'on top of the world']],
  [3, 'LAN4GUAGE', ['Foreign language', 'for in language']],
  [3, 'H I J K L M N O', ['Water', 'h to o', 'h2o'], 'From H to O.'],
  [2, 'X Q Q M E', ['Excuse me']],
  [2, 'NOON  GOOD', ['Good afternoon']],
  [2, 'G E S G', ['Scrambled eggs']],
  [2, 'P A W A L K R K', ['A walk in the park', 'walk in the park']],
  [2, 'BELT\n——————\nHITTING', ['Hitting below the belt', 'below the belt']],
];

export const RIDDLE_ITEMS = RIDDLES.map(([level, prompt, answers, hint]) => ({ level, prompt, answers, answerText: answers[0], hint }));
export const SITUATION_ITEMS = SITUATIONS.map(([level, prompt, answerText, answers]) => ({ level, prompt, answers, answerText }));
export const REBUS_ITEMS = REBUSES.map(([level, prompt, answers, hint]) => ({ level, prompt, answers, answerText: answers[0], hint }));
