// Prompts for the deep-thinking exercises. Written for this app.

// Explain it back (the Feynman technique): each concept lists the ideas a good explanation covers.
export const CONCEPTS = [
  { topic: 'Why the seasons happen', level: 1, points: ['Earth’s axis is tilted (about 23.5°)', 'the tilt, not the distance to the Sun, changes the seasons', 'summer = sunlight hits more directly and days are longer', 'the hemispheres have opposite seasons'] },
  { topic: 'How vaccines work', level: 1, points: ['they show the immune system a harmless version or piece of a germ', 'the body makes antibodies and memory cells', 'a later real infection is fought off faster', 'herd immunity protects people who can’t be vaccinated'] },
  { topic: 'Why the sky is blue', level: 1, points: ['sunlight contains all colours', 'air molecules scatter short (blue) wavelengths much more', 'sunsets are red because light crosses more air', 'the effect is called Rayleigh scattering'] },
  { topic: 'How a plane stays in the air', level: 2, points: ['wings push air downward (and the air pushes the wing up)', 'the wing’s angle and shape turn the airflow', 'engines provide thrust to keep air flowing over the wings', 'lift must balance weight; drag must be overcome'] },
  { topic: 'Compound interest', level: 1, points: ['you earn interest on your interest', 'growth speeds up over time (exponential)', 'time matters more than the starting amount', 'the same maths makes debt grow'] },
  { topic: 'Natural selection', level: 1, points: ['individuals vary', 'variation is inherited', 'some variants survive and reproduce more', 'over many generations the population changes'] },
  { topic: 'Supply and demand', level: 1, points: ['higher prices make people buy less', 'higher prices make producers supply more', 'the price settles where the two meet', 'shocks shift one of the curves'] },
  { topic: 'How the Internet sends a message', level: 2, points: ['data is split into packets', 'each packet carries addresses (IP)', 'routers pass packets along, maybe by different paths', 'packets are reassembled and missing ones re-sent (TCP)'] },
  { topic: 'Why we have tides', level: 2, points: ['the Moon’s gravity pulls unevenly across the Earth', 'there are two bulges, on the near and far sides', 'Earth rotates through them: about two tides a day', 'the Sun adds spring and neap tides'] },
  { topic: 'Entropy', level: 3, points: ['counts how many micro-arrangements fit a macro-state', 'disordered states have far more arrangements', 'so isolated systems drift toward them', 'this gives time its direction (the second law)'] },
  { topic: 'Opportunity cost', level: 1, points: ['every choice gives up the next best alternative', 'the cost is what you give up, not just the money', 'time has an opportunity cost too', 'it explains why “free” things still cost something'] },
  { topic: 'How memory works (encoding, storage, retrieval)', level: 2, points: ['attention decides what gets encoded', 'sleep helps consolidate memories', 'retrieving a memory strengthens it (testing effect)', 'spacing reviews beats cramming'] },
  { topic: 'Why ice floats', level: 1, points: ['water expands when it freezes', 'so ice is less dense than liquid water', 'hydrogen bonds hold ice in an open lattice', 'lakes freeze from the top, which protects life below'] },
  { topic: 'Photosynthesis', level: 1, points: ['plants take in carbon dioxide and water', 'light energy powers the reaction (in chloroplasts)', 'they make sugar (glucose) and release oxygen', 'it is the base of almost every food chain'] },
  { topic: 'How a refrigerator keeps food cold', level: 2, points: ['a fluid evaporates inside and absorbs heat', 'a compressor squeezes the vapour, heating it', 'the heat is released outside through the coils', 'it moves heat; it doesn’t make cold'] },
  { topic: 'Inflation', level: 2, points: ['the general level of prices rises', 'each unit of money buys less', 'causes include too much money chasing goods, or supply shocks', 'central banks raise interest rates to slow it'] },
  { topic: 'The placebo effect', level: 2, points: ['a treatment with no active ingredient can make people feel better', 'expectations and conditioning drive it', 'it mostly affects symptoms like pain, not the disease itself', 'drug trials compare against placebo for this reason'] },
  { topic: 'How GPS finds your position', level: 3, points: ['satellites broadcast precise time signals', 'the receiver measures how long each signal took', 'distances to 4+ satellites pin down position (trilateration)', 'relativity corrections keep the clocks accurate'] },
  { topic: 'Why correlation isn’t causation', level: 2, points: ['two things can move together by coincidence', 'a third factor can cause both (confounding)', 'the cause can run the other way', 'experiments with random assignment test causes'] },
  { topic: 'Plate tectonics', level: 2, points: ['the crust is broken into moving plates', 'they move a few centimetres a year, driven by the mantle', 'earthquakes and volcanoes cluster at plate edges', 'it explains mountains, ocean trenches and fitting coastlines'] },
  { topic: 'How a battery works', level: 2, points: ['two different materials want to exchange electrons', 'a chemical reaction pushes electrons through the outside circuit', 'ions move inside through the electrolyte', 'recharging runs the reaction backwards'] },
  { topic: 'Why the Moon shows phases', level: 1, points: ['half the Moon is always lit by the Sun', 'we see different amounts of the lit half as it orbits', 'it is not Earth’s shadow (that’s an eclipse)', 'one cycle takes about 29.5 days'] },
  { topic: 'Big O notation', level: 3, points: ['describes how running time grows with input size', 'ignores constants and small terms', 'examples: O(1), O(n), O(n log n), O(n²)', 'it lets you compare algorithms before running them'] },
  { topic: 'Confirmation bias', level: 1, points: ['we notice evidence that fits what we believe', 'we explain away evidence that doesn’t', 'it feels like careful thinking from the inside', 'antidote: look for what would prove you wrong'] },
  { topic: 'How antibiotics resistance spreads', level: 2, points: ['bacteria vary; a few survive the antibiotic', 'survivors multiply (natural selection)', 'resistance genes can be shared between bacteria', 'overuse and unfinished courses speed it up'] },
  { topic: 'Comparative advantage', level: 3, points: ['trade pays even if one side is better at everything', 'what matters is the relative (opportunity) cost', 'each side specialises in what it gives up least to make', 'both can end up with more'] },
  { topic: 'How the heart pumps blood', level: 1, points: ['four chambers: two atria, two ventricles', 'right side sends blood to the lungs, left side to the body', 'valves stop blood flowing backwards', 'an electrical signal times each beat'] },
  { topic: 'Why a hot-air balloon rises', level: 1, points: ['heated air expands and becomes less dense', 'the surrounding cooler air is heavier', 'buoyancy pushes the balloon up (Archimedes)', 'cooling the air lets it come down'] },
  { topic: 'Exponential growth', level: 2, points: ['grows by a fixed percentage each step', 'doubling time stays constant', 'it looks slow, then suddenly huge', 'nothing grows exponentially forever: limits kick in'] },
  { topic: 'How a bill becomes a law (anywhere you know)', level: 2, points: ['someone proposes it', 'it is debated and amended', 'it is voted on, often in more than one chamber', 'a head of state or court can approve, veto or strike it down'] },
];

// Steelman: argue the strongest version of a view (usually the one you don't hold).
export const STEELMAN = [
  'Homework should be abolished in primary schools.',
  'Cities should make public transport free.',
  'Zoos do more good than harm.',
  'Social media has made the world better overall.',
  'Voting should be compulsory.',
  'Nuclear power is essential to fight climate change.',
  'Everyone should learn to code at school.',
  'Tipping in restaurants should be replaced by higher wages.',
  'Space exploration is worth its cost.',
  'Standardised exams are the fairest way to select students.',
  'A four-day working week would be better for everyone.',
  'Cash should be phased out.',
  'Children should not have smartphones before age 14.',
  'Art made with AI tools is real art.',
  'Remote work is better than office work.',
  'Cars should be banned from city centres.',
  'Governments should tax sugary drinks.',
  'Museums should return artefacts to their countries of origin.',
  'Universities should be free for all students.',
  'Eating meat is morally wrong.',
  'Professional athletes are overpaid.',
  'Daylight saving time should be abolished.',
  'Grades do more harm than good.',
  'Genetic engineering of crops should be expanded.',
  'Video games are a legitimate art form.',
  'Everyone should do a year of national or community service.',
  'Billionaires should not exist.',
  'Privacy matters more than security.',
  'Learning Latin is a waste of time.',
  'The voting age should be lowered to 16.',
  'Advertising aimed at children should be banned.',
  'Handwriting should still be taught in schools.',
  'People should be allowed to sell their own organs.',
  'Tourism does more harm than good to popular cities.',
  'Old buildings should be protected even when housing is short.',
];

// First principles: strip a question to its basic facts, then rebuild an answer.
export const FIRST_PRINCIPLES = [
  { q: 'Why is a smartphone so expensive, and could one be made for a tenth of the price?', level: 2 },
  { q: 'How would you estimate how long it takes to fill an Olympic swimming pool with a garden hose?', level: 1 },
  { q: 'Why do bicycles stay upright when moving but fall over when still?', level: 2 },
  { q: 'Design a way to measure the height of a tall building using only a ball and a stopwatch.', level: 2 },
  { q: 'Why are most roads and houses built the way they are? Could they be built another way?', level: 3 },
  { q: 'How would you get fresh water on a small island with no rivers?', level: 2 },
  { q: 'Why do we have weekends? What would change if we didn’t?', level: 1 },
  { q: 'How would you decide whether a new school rule is actually working?', level: 1 },
  { q: 'Why does a restaurant charge what it does for a pizza? Break the price down.', level: 1 },
  { q: 'How could you keep a house cool in summer without air conditioning?', level: 2 },
  { q: 'Why do cities exist at all? What makes people crowd together?', level: 3 },
  { q: 'How would you teach someone to cook if neither of you could read?', level: 2 },
  { q: 'Why are rockets so expensive, and what would have to change to make launches cheap?', level: 3 },
  { q: 'How would you find out how many piano tuners work in your city?', level: 1 },
  { q: 'What does a library really do? Could you design a better one from scratch?', level: 2 },
  { q: 'How would you learn a new language as fast as possible, from zero?', level: 1 },
  { q: 'Why do we sleep? List what you know for sure and what is only a guess.', level: 3 },
  { q: 'How would you make a town safer for cyclists without spending much money?', level: 2 },
  { q: 'Why do batteries run out, and what limits how much energy they can hold?', level: 3 },
  { q: 'How would you tell whether a news story is true, starting only from what you can check yourself?', level: 2 },
  { q: 'Why do shops put milk at the back? What does that tell you about how shops are designed?', level: 1 },
  { q: 'How would you measure the speed of sound with things you have at home?', level: 2 },
  { q: 'What is a price? Explain it without using the words money, cost or value.', level: 3 },
  { q: 'Why do bridges look so different from each other? What problem is each shape solving?', level: 3 },
  { q: 'How much food does a city of one million people need each day, and how does it get there?', level: 2 },
];

// No-AI challenge of the day: small real-world tasks done by hand, with your own head.
export const CHALLENGES = [
  'Get somewhere new today using a map you studied beforehand, without turn-by-turn directions.',
  'Do a long multiplication by hand (at least 3 digits × 3 digits), then check it by estimating.',
  'Write a one-page letter by hand to someone, and actually send it.',
  'Cook a meal without following a recipe.',
  'Memorise a short poem (8+ lines) and recite it to someone this evening.',
  'Work out your monthly spending by category, using only pen and paper.',
  'Fix something broken at home without looking up a tutorial first.',
  'Read a chapter of a book and write a five-sentence summary from memory.',
  'Sketch a map of your neighbourhood from memory, then check it.',
  'Learn 10 words in a new language using flashcards you make yourself.',
  'Plan tomorrow in detail on paper, then check tonight how well you followed it.',
  'Find the answer to a question you are curious about using a physical book or a library.',
  'Estimate the height of a building or tree near you, and explain your method.',
  'Go for a 20-minute walk with no phone, then write down three things you noticed.',
  'Explain something you know well to a friend without notes or slides.',
  'Solve a Sudoku or crossword on paper without any hints.',
  'Make a decision you have been putting off, writing down the pros and cons by hand first.',
  'Draw an object in front of you for 15 minutes, paying attention to its real shape.',
  'Mentally calculate the total of your shopping before you reach the till.',
  'Write down, from memory, the phone numbers of three people you would call in an emergency.',
  'Tell the time at night or find north using the sky, and check with a compass or phone afterwards.',
  'Write a short story (200 words) with a beginning, a twist and an end.',
  'Have a conversation where you only ask questions for the first five minutes.',
  'Look up nothing for a whole evening: keep a list of the questions you wanted to search, and try to reason them out.',
  'Build something small with your hands: a paper model, a shelf, a knot you didn’t know.',
  'Explain in writing how something in your home works (a tap, a lock, a toaster) and then check.',
  'Teach a child or friend a game, from the rules to the first win.',
  'Write down one thing you believe, and three facts that would change your mind about it.',
  'Keep a paper log of how you spend every hour today.',
  'Do a 10-minute mental-arithmetic set: add up everything you see prices for today.',
];
