// Offline trivia: original questions on well-established facts. Each row:
//   [category, level 1–3, question, correct answer, wrong, wrong, wrong]
const ROWS = [
  // science
  ['Science', 1, 'What gas do plants take in from the air for photosynthesis?', 'Carbon dioxide', 'Oxygen', 'Nitrogen', 'Hydrogen'],
  ['Science', 1, 'What is the chemical symbol for gold?', 'Au', 'Ag', 'Gd', 'Go'],
  ['Science', 1, 'How many bones are in the adult human body?', '206', '186', '226', '306'],
  ['Science', 1, 'What is the hardest natural substance?', 'Diamond', 'Quartz', 'Granite', 'Topaz'],
  ['Science', 1, 'Which planet is known as the Red Planet?', 'Mars', 'Venus', 'Jupiter', 'Mercury'],
  ['Science', 1, 'What is the largest organ of the human body?', 'The skin', 'The liver', 'The brain', 'The lungs'],
  ['Science', 1, 'At what temperature (°C) does water boil at sea level?', '100', '90', '120', '80'],
  ['Science', 2, 'What part of the cell contains most of its DNA?', 'The nucleus', 'The ribosome', 'The cell membrane', 'The cytoplasm'],
  ['Science', 2, 'Which element has the atomic number 1?', 'Hydrogen', 'Helium', 'Oxygen', 'Carbon'],
  ['Science', 2, 'What is the most abundant gas in Earth’s atmosphere?', 'Nitrogen', 'Oxygen', 'Argon', 'Carbon dioxide'],
  ['Science', 2, 'Which scientist proposed the three laws of motion?', 'Isaac Newton', 'Galileo Galilei', 'Albert Einstein', 'Johannes Kepler'],
  ['Science', 2, 'What is the SI unit of electrical resistance?', 'Ohm', 'Volt', 'Ampere', 'Watt'],
  ['Science', 2, 'Which blood cells carry oxygen?', 'Red blood cells', 'White blood cells', 'Platelets', 'Plasma cells'],
  ['Science', 2, 'What is the main component of the Sun?', 'Hydrogen', 'Helium', 'Oxygen', 'Iron'],
  ['Science', 2, 'Which vitamin does the skin make in sunlight?', 'Vitamin D', 'Vitamin C', 'Vitamin A', 'Vitamin K'],
  ['Science', 2, 'What kind of animal is a Komodo dragon?', 'A lizard', 'A snake', 'A crocodile', 'A salamander'],
  ['Science', 3, 'What is the only metal that is liquid at room temperature?', 'Mercury', 'Gallium', 'Caesium', 'Bromine'],
  ['Science', 3, 'Which subatomic particle has no electric charge?', 'Neutron', 'Proton', 'Electron', 'Positron'],
  ['Science', 3, 'Roughly how long does light from the Sun take to reach Earth?', 'About 8 minutes', 'About 8 seconds', 'About 8 hours', 'About 1 minute'],
  ['Science', 3, 'Which organelle is called the powerhouse of the cell?', 'Mitochondrion', 'Golgi apparatus', 'Lysosome', 'Chloroplast'],
  ['Science', 3, 'What is the pH of pure water at 25 °C?', '7', '0', '14', '5'],
  ['Science', 3, 'Who discovered penicillin’s antibacterial effect in 1928?', 'Alexander Fleming', 'Louis Pasteur', 'Joseph Lister', 'Robert Koch'],
  ['Science', 3, 'Which planet has the shortest day?', 'Jupiter', 'Mercury', 'Earth', 'Mars'],
  ['Science', 3, 'What does DNA stand for?', 'Deoxyribonucleic acid', 'Dinitrogen acid', 'Deoxyribose nitrate', 'Dual nucleic acid'],
  // geography
  ['Geography', 1, 'What is the largest ocean on Earth?', 'Pacific Ocean', 'Atlantic Ocean', 'Indian Ocean', 'Arctic Ocean'],
  ['Geography', 1, 'Which is the largest country by area?', 'Russia', 'Canada', 'China', 'United States'],
  ['Geography', 1, 'On which continent is the Sahara Desert?', 'Africa', 'Asia', 'Australia', 'South America'],
  ['Geography', 1, 'What is the capital of Japan?', 'Tokyo', 'Kyoto', 'Osaka', 'Seoul'],
  ['Geography', 1, 'Which river flows through Paris?', 'The Seine', 'The Thames', 'The Rhine', 'The Danube'],
  ['Geography', 2, 'What is the tallest mountain above sea level?', 'Mount Everest', 'K2', 'Kangchenjunga', 'Denali'],
  ['Geography', 2, 'Which country has the most people?', 'India', 'China', 'United States', 'Indonesia'],
  ['Geography', 2, 'Which is the smallest country in the world by area?', 'Vatican City', 'Monaco', 'San Marino', 'Liechtenstein'],
  ['Geography', 2, 'The Andes mountains run along which side of South America?', 'West', 'East', 'North', 'South'],
  ['Geography', 2, 'Which country is home to the ancient city of Petra?', 'Jordan', 'Egypt', 'Syria', 'Lebanon'],
  ['Geography', 2, 'What is the capital of Canada?', 'Ottawa', 'Toronto', 'Montreal', 'Vancouver'],
  ['Geography', 2, 'Which strait separates Europe and Africa?', 'The Strait of Gibraltar', 'The Bosphorus', 'The Strait of Hormuz', 'The Bering Strait'],
  ['Geography', 3, 'What is the deepest lake in the world?', 'Lake Baikal', 'Lake Tanganyika', 'Lake Superior', 'Caspian Sea'],
  ['Geography', 3, 'Which country has the most islands?', 'Sweden', 'Indonesia', 'Philippines', 'Japan'],
  ['Geography', 3, 'Which African country was formerly called Abyssinia?', 'Ethiopia', 'Eritrea', 'Somalia', 'Sudan'],
  ['Geography', 3, 'What is the driest non-polar desert on Earth?', 'The Atacama', 'The Sahara', 'The Gobi', 'The Kalahari'],
  ['Geography', 3, 'Which two countries share the longest international border?', 'Canada and the United States', 'Russia and Kazakhstan', 'Chile and Argentina', 'China and Mongolia'],
  ['Geography', 3, 'The Danube empties into which sea?', 'The Black Sea', 'The Mediterranean', 'The Baltic Sea', 'The Adriatic Sea'],
  // history
  ['History', 1, 'Who was the first person to walk on the Moon?', 'Neil Armstrong', 'Buzz Aldrin', 'Yuri Gagarin', 'John Glenn'],
  ['History', 1, 'In which country were the ancient pyramids of Giza built?', 'Egypt', 'Mexico', 'Iraq', 'Greece'],
  ['History', 1, 'Which ship sank on its maiden voyage in 1912?', 'Titanic', 'Lusitania', 'Britannic', 'Queen Mary'],
  ['History', 1, 'Who was the first President of the United States?', 'George Washington', 'Thomas Jefferson', 'Abraham Lincoln', 'John Adams'],
  ['History', 2, 'In what year did the Berlin Wall fall?', '1989', '1979', '1991', '1985'],
  ['History', 2, 'Which empire built Machu Picchu?', 'The Inca', 'The Aztec', 'The Maya', 'The Olmec'],
  ['History', 2, 'Who was the first emperor of Rome?', 'Augustus', 'Julius Caesar', 'Nero', 'Caligula'],
  ['History', 2, 'Which war was fought between the North and South of the United States?', 'The Civil War', 'The War of 1812', 'The Revolutionary War', 'The Spanish–American War'],
  ['History', 2, 'Which civilisation invented cuneiform writing?', 'The Sumerians', 'The Egyptians', 'The Phoenicians', 'The Chinese'],
  ['History', 2, 'In which year did World War II end?', '1945', '1944', '1946', '1939'],
  ['History', 2, 'Who led the Salt March in India in 1930?', 'Mahatma Gandhi', 'Jawaharlal Nehru', 'Subhas Chandra Bose', 'B. R. Ambedkar'],
  ['History', 3, 'Which treaty ended World War I with Germany?', 'The Treaty of Versailles', 'The Treaty of Paris', 'The Treaty of Ghent', 'The Treaty of Utrecht'],
  ['History', 3, 'Who was the Carthaginian general who crossed the Alps with elephants?', 'Hannibal', 'Hamilcar', 'Scipio', 'Hasdrubal'],
  ['History', 3, 'In what year did Constantinople fall to the Ottomans?', '1453', '1492', '1204', '1517'],
  ['History', 3, 'Which dynasty built most of the Great Wall that stands today?', 'The Ming', 'The Qin', 'The Han', 'The Tang'],
  ['History', 3, 'Who wrote the Communist Manifesto with Karl Marx?', 'Friedrich Engels', 'Vladimir Lenin', 'Leon Trotsky', 'Rosa Luxemburg'],
  ['History', 3, 'Which Mali emperor made a famous, gold-laden pilgrimage to Mecca in 1324?', 'Mansa Musa', 'Sundiata Keita', 'Sonni Ali', 'Askia Muhammad'],
  // arts and literature
  ['Arts', 1, 'Who painted the Mona Lisa?', 'Leonardo da Vinci', 'Michelangelo', 'Raphael', 'Botticelli'],
  ['Arts', 1, 'Who wrote Romeo and Juliet?', 'William Shakespeare', 'Christopher Marlowe', 'Charles Dickens', 'Jane Austen'],
  ['Arts', 1, 'How many keys does a standard piano have?', '88', '76', '96', '64'],
  ['Arts', 2, 'Who painted The Starry Night?', 'Vincent van Gogh', 'Claude Monet', 'Paul Cézanne', 'Edvard Munch'],
  ['Arts', 2, 'Which author created Sherlock Holmes?', 'Arthur Conan Doyle', 'Agatha Christie', 'Edgar Allan Poe', 'Wilkie Collins'],
  ['Arts', 2, 'Which composer became deaf but kept composing, including his Ninth Symphony?', 'Ludwig van Beethoven', 'Wolfgang Amadeus Mozart', 'Johann Sebastian Bach', 'Franz Schubert'],
  ['Arts', 2, 'In which city is the Louvre museum?', 'Paris', 'Rome', 'Madrid', 'Vienna'],
  ['Arts', 2, 'Who wrote One Hundred Years of Solitude?', 'Gabriel García Márquez', 'Jorge Luis Borges', 'Isabel Allende', 'Mario Vargas Llosa'],
  ['Arts', 2, 'Which art movement is Salvador Dalí best known for?', 'Surrealism', 'Cubism', 'Impressionism', 'Baroque'],
  ['Arts', 3, 'Who wrote the epic poem Paradise Lost?', 'John Milton', 'Geoffrey Chaucer', 'Edmund Spenser', 'William Blake'],
  ['Arts', 3, 'Which Japanese artist made The Great Wave off Kanagawa?', 'Hokusai', 'Hiroshige', 'Utamaro', 'Sesshū'],
  ['Arts', 3, 'Who wrote Don Quixote?', 'Miguel de Cervantes', 'Lope de Vega', 'Federico García Lorca', 'Benito Pérez Galdós'],
  ['Arts', 3, 'Which Russian author wrote Crime and Punishment?', 'Fyodor Dostoevsky', 'Leo Tolstoy', 'Anton Chekhov', 'Ivan Turgenev'],
  ['Arts', 3, 'Frida Kahlo was a painter from which country?', 'Mexico', 'Spain', 'Argentina', 'Colombia'],
  // maths and technology
  ['Maths', 1, 'What is 12 × 12?', '144', '124', '132', '156'],
  ['Maths', 1, 'How many sides does a hexagon have?', '6', '5', '7', '8'],
  ['Maths', 2, 'What is the square root of 169?', '13', '12', '14', '17'],
  ['Maths', 2, 'What is the sum of the angles in a triangle?', '180°', '90°', '270°', '360°'],
  ['Maths', 2, 'What is the next prime number after 7?', '11', '9', '13', '10'],
  ['Maths', 2, 'Roughly what is pi to two decimal places?', '3.14', '3.41', '3.12', '3.16'],
  ['Maths', 3, 'What is 2 to the power of 10?', '1024', '512', '2048', '1000'],
  ['Maths', 3, 'Which mathematician is known for the theorem a² + b² = c²?', 'Pythagoras', 'Euclid', 'Archimedes', 'Thales'],
  ['Maths', 3, 'How many degrees are in one radian, roughly?', '57.3', '45', '90', '60'],
  ['Maths', 3, 'What is the only even prime number?', '2', '4', '0', '6'],
  ['Technology', 1, 'What does “www” stand for in a web address?', 'World Wide Web', 'World Web Wire', 'Wide World Web', 'Web World Wide'],
  ['Technology', 2, 'Who is often called the father of the computer for designing the Analytical Engine?', 'Charles Babbage', 'Alan Turing', 'John von Neumann', 'Blaise Pascal'],
  ['Technology', 2, 'Which company made the first commercially successful microprocessor, the 4004?', 'Intel', 'IBM', 'Motorola', 'Texas Instruments'],
  ['Technology', 2, 'Who wrote what is often called the first computer program, for the Analytical Engine?', 'Ada Lovelace', 'Grace Hopper', 'Hedy Lamarr', 'Margaret Hamilton'],
  ['Technology', 3, 'Who invented the World Wide Web?', 'Tim Berners-Lee', 'Vint Cerf', 'Bill Gates', 'Steve Jobs'],
  ['Technology', 3, 'How many bits are in a byte?', '8', '4', '16', '10'],
  ['Technology', 3, 'What does CPU stand for?', 'Central processing unit', 'Computer power unit', 'Central program utility', 'Core processing unit'],
  // nature
  ['Nature', 1, 'What is the fastest land animal?', 'The cheetah', 'The lion', 'The pronghorn', 'The horse'],
  ['Nature', 1, 'What is the largest animal that has ever lived?', 'The blue whale', 'The African elephant', 'Argentinosaurus', 'The whale shark'],
  ['Nature', 1, 'How many legs does a spider have?', '8', '6', '10', '12'],
  ['Nature', 2, 'What is a group of lions called?', 'A pride', 'A pack', 'A herd', 'A troop'],
  ['Nature', 2, 'Which bird is the largest living bird?', 'The ostrich', 'The emu', 'The albatross', 'The condor'],
  ['Nature', 2, 'What do bees make from nectar?', 'Honey', 'Wax', 'Propolis', 'Royal jelly'],
  ['Nature', 2, 'Which is the tallest type of tree?', 'Coast redwood', 'Giant sequoia', 'Douglas fir', 'Baobab'],
  ['Nature', 2, 'What is the only mammal that can truly fly?', 'The bat', 'The flying squirrel', 'The sugar glider', 'The colugo'],
  ['Nature', 3, 'Which mammal has the longest pregnancy?', 'The African elephant', 'The blue whale', 'The giraffe', 'The rhinoceros'],
  ['Nature', 3, 'Axolotls are a kind of what?', 'Salamander', 'Fish', 'Lizard', 'Frog'],
  ['Nature', 3, 'What gives flamingos their pink colour?', 'Pigments in their food', 'Their blood', 'Sunlight', 'A skin disease'],
  ['Nature', 3, 'How many hearts does an octopus have?', '3', '1', '2', '8'],
  // language and ideas
  ['Language', 1, 'What is the opposite of “ancient”?', 'Modern', 'Old', 'Historic', 'Antique'],
  ['Language', 2, 'Which language has the most native speakers?', 'Mandarin Chinese', 'Spanish', 'English', 'Hindi'],
  ['Language', 2, 'What is a word that reads the same backwards, like “level”?', 'A palindrome', 'An anagram', 'A homophone', 'An acronym'],
  ['Language', 2, 'Which alphabet is used to write Russian?', 'Cyrillic', 'Greek', 'Latin', 'Georgian'],
  ['Language', 3, 'From which language does the word “kindergarten” come?', 'German', 'Dutch', 'Danish', 'Swedish'],
  ['Language', 3, 'What is the study of word origins called?', 'Etymology', 'Entomology', 'Phonology', 'Morphology'],
  ['Philosophy', 2, 'Which Greek philosopher was Plato’s teacher?', 'Socrates', 'Aristotle', 'Pythagoras', 'Heraclitus'],
  ['Philosophy', 2, 'Who said “I think, therefore I am”?', 'René Descartes', 'Immanuel Kant', 'John Locke', 'Baruch Spinoza'],
  ['Philosophy', 3, 'Who wrote The Wealth of Nations (1776)?', 'Adam Smith', 'David Hume', 'John Stuart Mill', 'David Ricardo'],
  ['Philosophy', 3, 'Which philosopher described the “categorical imperative”?', 'Immanuel Kant', 'G. W. F. Hegel', 'Friedrich Nietzsche', 'Jeremy Bentham'],
  // space
  ['Space', 1, 'What is the closest star to Earth?', 'The Sun', 'Proxima Centauri', 'Sirius', 'Polaris'],
  ['Space', 1, 'What is the largest planet in the Solar System?', 'Jupiter', 'Saturn', 'Neptune', 'Earth'],
  ['Space', 2, 'Who was the first human in space?', 'Yuri Gagarin', 'Neil Armstrong', 'Alan Shepard', 'Valentina Tereshkova'],
  ['Space', 2, 'Which planet is famous for its prominent rings?', 'Saturn', 'Mars', 'Venus', 'Mercury'],
  ['Space', 2, 'What is the name of our galaxy?', 'The Milky Way', 'Andromeda', 'The Triangulum', 'The Whirlpool'],
  ['Space', 3, 'Which was the first artificial satellite, launched in 1957?', 'Sputnik 1', 'Explorer 1', 'Vostok 1', 'Telstar'],
  ['Space', 3, 'What is the hottest planet in the Solar System?', 'Venus', 'Mercury', 'Mars', 'Jupiter'],
  ['Space', 3, 'What is a light-year a measure of?', 'Distance', 'Time', 'Brightness', 'Speed'],
  ['Space', 3, 'Which dwarf planet was reclassified from planet in 2006?', 'Pluto', 'Ceres', 'Eris', 'Haumea'],
  // sport and games
  ['Sport', 1, 'How many players are on a football (soccer) team on the pitch?', '11', '10', '9', '12'],
  ['Sport', 2, 'In chess, which piece can only move diagonally?', 'The bishop', 'The rook', 'The knight', 'The king'],
  ['Sport', 2, 'Where were the first modern Olympic Games held in 1896?', 'Athens', 'Paris', 'London', 'Rome'],
  ['Sport', 2, 'How long is a marathon, roughly?', '42.2 km', '40 km', '26.2 km', '50 km'],
  ['Sport', 3, 'In tennis, what is a score of zero called?', 'Love', 'Nil', 'Duck', 'Zip'],
  ['Sport', 3, 'How many squares are on a chessboard?', '64', '81', '100', '49'],
];

export const TRIVIA = ROWS.map(([category, level, q, a, ...wrong]) => ({ category, level, q, a, wrong }));
